idf_component_register(SRCS "main.c"
                            "face.c"
                            "vapi_media.c"
                            "vapi_client.c"
                            "vapi_app.c"
                            "wifi.c"
                            "vision.c"
                            "model_flash.c"
                       INCLUDE_DIRS ".")
