/* General settings for the Vapi Watcher Face. */

#pragma once

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* This board has no AEC.
 *
 * The AtomS3R could cancel echo because one ES8311 served mic and speaker and
 * could loop the DAC back into the ADC as a reference. Here the speaker is an
 * ES8311 and the microphone an ES7243/ES7243E — two separate chips, so no such
 * reference exists. Echo is handled entirely by VAPI_ECHO_GATE below, which is
 * what actually worked on the AtomS3R anyway.
 */

/**
 * @brief  Wire audio format. Fixed, and deliberately not configurable.
 *
 * Vapi's `vapi.websocket` transport carries **raw PCM** — no Opus, no RTP.
 * Binary websocket frames are audio, text frames are JSON control messages.
 *
 * 16 kHz is the right rate and the reason is measured, not assumed: Vapi accepts
 * 16000 / 24000 / 48000 and honours all three, but its returned audio has no
 * real content above 8 kHz (measured 36 dB down at 48 kHz). Higher rates only
 * upsample, tripling bytes for nothing — and on this board bytes are WiFi
 * airtime.
 *
 * At 16 kHz / mono / s16le this is 256 kbit/s in each direction. That is ~16x
 * what Opus would cost and is the price of Vapi having no compressed-audio
 * transport that an MCU can reach; it is still comfortable on 802.11n.
 */
#define VAPI_SAMPLE_RATE   (16000)
#define VAPI_CHANNELS      (1)
#define VAPI_BITS_PER_SAMP (16)

/**
 * @brief  Audio chunk sent per websocket frame, in milliseconds.
 *
 * 20 ms (640 bytes at 16 kHz mono s16le) matches the packetisation every other
 * realtime audio path uses and keeps the send task's duty cycle predictable.
 * Larger frames cut websocket overhead but add latency in whole chunks.
 */
#define VAPI_FRAME_MS (20)

/** Bytes in one outbound audio frame. */
#define VAPI_FRAME_BYTES \
    ((VAPI_SAMPLE_RATE / 1000) * VAPI_FRAME_MS * VAPI_CHANNELS * (VAPI_BITS_PER_SAMP / 8))

/* Pull in ENV_* overrides generated from .env at configure time (if any).
 * Generated by tools/gen_env_header.py; see .env.example. */
#if defined(__has_include)
#  if __has_include("env_config.generated.h")
#    include "env_config.generated.h"
#  endif
#endif

/* --- Runtime config --------------------------------------------------------
 * Each setting comes from a `.env` file if present (turned into an ENV_* macro
 * by CMake — see CMakeLists.txt and .env.example), otherwise falls back to the
 * `idf.py menuconfig` value (Kconfig.projbuild).
 */
#ifdef ENV_WIFI_SSID
#define WIFI_SSID ENV_WIFI_SSID
#else
#define WIFI_SSID CONFIG_VAPI_WIFI_SSID
#endif

#ifdef ENV_WIFI_PASSWORD
#define WIFI_PASSWORD ENV_WIFI_PASSWORD
#else
#define WIFI_PASSWORD CONFIG_VAPI_WIFI_PASSWORD
#endif

#ifdef ENV_VAPI_API_URL
#define VAPI_API_URL ENV_VAPI_API_URL
#else
#define VAPI_API_URL CONFIG_VAPI_API_URL
#endif

#ifdef ENV_VAPI_API_KEY
#define VAPI_API_KEY ENV_VAPI_API_KEY
#else
#define VAPI_API_KEY CONFIG_VAPI_API_KEY
#endif

#ifdef ENV_VAPI_ASSISTANT_ID
#define VAPI_ASSISTANT_ID ENV_VAPI_ASSISTANT_ID
#else
#define VAPI_ASSISTANT_ID CONFIG_VAPI_ASSISTANT_ID
#endif

#ifdef ENV_VAPI_FIRST_MESSAGE
#define VAPI_FIRST_MESSAGE ENV_VAPI_FIRST_MESSAGE
#else
#define VAPI_FIRST_MESSAGE CONFIG_VAPI_FIRST_MESSAGE
#endif

#ifdef ENV_VAPI_MAX_DURATION_SECONDS
#define VAPI_MAX_DURATION_SECONDS ENV_VAPI_MAX_DURATION_SECONDS
#else
#define VAPI_MAX_DURATION_SECONDS CONFIG_VAPI_MAX_DURATION_SECONDS
#endif

/**
 * @brief  Microphone analog input gain, in dB.
 *
 * The codec comes up at **30 dB**, which is far too hot for a mic sitting
 * centimetres from the speaker: measured on this board, a tone played at
 * volume 85 arrives at the mic **+8.8 dB louder than the AEC's echo
 * reference**, and the canceller cannot converge on an echo that dominates its
 * own reference. The result is total passthrough — the assistant hears itself
 * and talks to itself in a loop.
 *
 * The reference is a bit-exact digital copy of what is written to the DAC
 * (measured: constant at peak 9000 for a 9000-amplitude tone, unchanged across
 * the whole volume range), so it is untouched by analog mic gain. That makes
 * mic gain the right knob: it lowers the echo without lowering the reference,
 * and unlike turning the speaker down it costs nothing in loudness.
 *
 * Measured at speaker volume 85 (echo level relative to the reference):
 *
 *     30 dB  ->  +8.8 dB   AEC cannot converge  (the shipped default, broken)
 *     24 dB  ->  +2.8 dB   still above the reference
 *     18 dB  ->  -3.2 dB   <- chosen: headroom, mic still sensitive
 *     12 dB  ->  -9.2 dB   quieter still; far-field pickup starts to suffer
 *      0 dB  -> -21.3 dB   echo gone, and so is the user
 *
 * Tune live with the `gain <db>` console command; re-run the boot probe
 * (VAPI_AEC_PROBE) after moving the speaker or changing the enclosure.
 *
 * Cutting analog gain alone is only half the fix — see
 * VAPI_MIC_DIGITAL_GAIN_DB.
 */
#define VAPI_MIC_GAIN_DB (24.0f)

/**
 * @brief  Digital makeup gain applied *after* the AEC, in dB.
 *
 * Dropping the analog mic gain from 30 dB to 18 dB is what lets the AEC
 * converge, but it attenuates the whole input — and the speaker is ~2 cm from
 * the mic while the talker is ~40 cm away, so it costs the talker far more than
 * it costs the echo. Measured consequence of analog-only: echo gone, and Vapi
 * received nothing at all ("Are you still there?" three times, zero `user:`
 * transcripts).
 *
 * So the level is made back up *downstream of the canceller*, where the echo
 * has already been removed: the talker comes back, the echo does not. This is
 * precisely the job the AFE's own AGC would do, except that
 * `voice_communication_agc_init` is inside an `#if 0` upstream in
 * esp-webrtc-solution (capture_aud_aec_src.c) and references a variable that no
 * longer exists in that function, so it cannot simply be switched on.
 *
 * +12 dB exactly restores the 12 dB given up on the analog side. It also lifts
 * the AEC's residual echo and the noise floor by 12 dB, which is fine only
 * because cancellation happens first — applying this before the AEC would
 * simply undo the fix.
 *
 * Tune live with `dgain <db>`. Raise if Vapi still mishears; lower if you hear
 * the residual echo come back or speech sounds crushed.
 */
#define VAPI_MIC_DIGITAL_GAIN_DB (6.0f)

/**
 * @brief  Run the boot-time AEC echo-reference probe (diagnostic).
 *
 * Plays a tone and reports the RMS of each raw capture slot, plus ES8311
 * register 0x44. Set to 0 for normal builds; it adds ~1 s to boot and briefly
 * drives the speaker. See aec_probe.c.
 */
#define VAPI_AEC_PROBE (0)

/**
 * @brief  Suppress the microphone while the assistant is audible.
 *
 * The last line of defence, and on this board it is load-bearing rather than
 * belt-and-braces. Measured: esp-sr's AFE cancels so little on this hardware
 * that its *residual* echo is still transcribed as user speech even after the
 * echo entering the mic was cut by 12.5 dB. Tuning gain cannot fix that —
 * analog and digital gain scale echo and talker together, and turning the
 * speaker down far enough to hide the residual would make the device inaudible.
 *
 * Why we can do better than the AEC here: we write every inbound frame to the
 * speaker ourselves, so we know exactly what the far end is about to say, and
 * `av_render_get_audio_fifo_level()` tells us how long until it actually comes
 * out. That gives a *delay-compensated* gate — no guessing, unlike gating on
 * Vapi's `speech-update` messages, which arrive on network time and are not
 * aligned with the audio at all.
 *
 * The cost is barge-in: while the assistant is speaking the mic is attenuated,
 * so you cannot interrupt it by talking over it. That is the honest trade on
 * hardware whose speaker sits 2 cm from its microphone. Tap the button or use
 * the long-press assistant mute to cut it off instead.
 */
#define VAPI_ECHO_GATE (1)

/** How hard to attenuate the mic while the far end is audible, in dB.
 *  Attenuate rather than hard-mute: a stream of true digital silence can make
 *  the far end think the link died. 40 dB is inaudible without being zero. */
#define VAPI_ECHO_GATE_ATTEN_DB (60.0f)   /* 60 = hard mute */

/** Keep the gate shut this long after the far end goes quiet, to cover the
 *  room's reverb tail and any jitter in the FIFO-latency estimate. */
#define VAPI_ECHO_GATE_HANGOVER_MS (400)

/** Inbound RMS above which the far end counts as speaking. Vapi sends
 *  continuous audio including near-silence between phrases, so this has to sit
 *  above the comfort-noise floor or the gate never opens. */
#define VAPI_ECHO_GATE_THRESHOLD (300)

/**
 * @brief  Wake a call when the camera sees someone.
 *
 * The Himax runs detection locally and continuously, so this costs nothing per
 * frame — unlike waiting for a wake word, which would need the microphone open
 * the whole time.
 */
#define VISION_WAKE_ON_PRESENCE (1)

/**
 * @brief  Keep the most recent JPEG frame in memory.
 *
 * Needed to show a cloud VLM what the device saw. Costs PSRAM per frame and
 * makes the Himax push the image over SPI on every inference, so leave it off
 * until the VLM path is actually wired up.
 */
#define VISION_KEEP_FRAMES (0)

/**
 * @brief  Ask the Himax to identify itself and its model at startup.
 *
 * Off because it does not work here and is expensive to find out: this device's
 * Himax firmware never answers NAME?/VERSION?, and sscma_client retries for
 * ~20 seconds per query before giving up. Purely diagnostic — inference runs
 * fine without it.
 */
#define VISION_QUERY_INFO (0)

/**
 * @brief  Default speaker volume (0-100). The codec accepts up to 100; 90
 *         leaves a little headroom against distortion and current draw.
 *
 * This was 60 for a while, then 78, because echo scaled with it. That no longer
 * applies: VAPI_ECHO_GATE hard-mutes the microphone whenever the assistant is
 * audible, so however loud the speaker gets, none of it reaches Vapi. Echo
 * stopped being the constraint on loudness the moment the gate started working.
 *
 * What limits it now is physical, not acoustic:
 *   - the Echo Base speaker is small and will distort before it runs out of
 *     digital range, so back off with `vol -10` if it sounds harsh rather than
 *     merely loud;
 *   - the board is bus-powered and the amplifier draws real current. A mid-call
 *     reboot on the sibling firmware was a genuine `power-on` reset, not a
 *     crash. Running at 100 makes that likelier on a weak USB port — use a
 *     powered hub, and check the reset reason printed at boot before blaming
 *     the code.
 */
#define DEFAULT_PLAYBACK_VOL (90)

#ifdef __cplusplus
}
#endif
