/* General settings for the Vapi Watcher Face. */

#pragma once

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* This board has no AEC.
 *
 * The AtomS3R could cancel echo because one ES8311 served mic and speaker and
 * could loop the DAC back into the ADC as a reference. Here the speaker is an
 * ES8311 and the microphone an ES7243/ES7243E — two separate chips, so no such
 * reference exists. Echo is handled entirely by VAPI_ECHO_GATE below, which is
 * what actually worked on the AtomS3R anyway.
 */

/**
 * @brief  Wire audio format. Fixed, and deliberately not configurable.
 *
 * Vapi's `vapi.websocket` transport carries **raw PCM** — no Opus, no RTP.
 * Binary websocket frames are audio, text frames are JSON control messages.
 *
 * 16 kHz is the right rate and the reason is measured, not assumed: Vapi accepts
 * 16000 / 24000 / 48000 and honours all three, but its returned audio has no
 * real content above 8 kHz (measured 36 dB down at 48 kHz). Higher rates only
 * upsample, tripling bytes for nothing — and on this board bytes are WiFi
 * airtime.
 *
 * At 16 kHz / mono / s16le this is 256 kbit/s in each direction. That is ~16x
 * what Opus would cost and is the price of Vapi having no compressed-audio
 * transport that an MCU can reach; it is still comfortable on 802.11n.
 */
#define VAPI_SAMPLE_RATE   (16000)
#define VAPI_CHANNELS      (1)
#define VAPI_BITS_PER_SAMP (16)

/**
 * @brief  Audio chunk sent per websocket frame, in milliseconds.
 *
 * 20 ms (640 bytes at 16 kHz mono s16le) matches the packetisation every other
 * realtime audio path uses and keeps the send task's duty cycle predictable.
 * Larger frames cut websocket overhead but add latency in whole chunks.
 */
#define VAPI_FRAME_MS (20)

/** Bytes in one outbound audio frame. */
#define VAPI_FRAME_BYTES \
    ((VAPI_SAMPLE_RATE / 1000) * VAPI_FRAME_MS * VAPI_CHANNELS * (VAPI_BITS_PER_SAMP / 8))

/* Pull in ENV_* overrides generated from .env at configure time (if any).
 * Generated by tools/gen_env_header.py; see .env.example. */
#if defined(__has_include)
#  if __has_include("env_config.generated.h")
#    include "env_config.generated.h"
#  endif
#endif

/* --- Runtime config --------------------------------------------------------
 * Each setting comes from a `.env` file if present (turned into an ENV_* macro
 * by CMake — see CMakeLists.txt and .env.example), otherwise falls back to the
 * `idf.py menuconfig` value (Kconfig.projbuild).
 */
#ifdef ENV_WIFI_SSID
#define WIFI_SSID ENV_WIFI_SSID
#else
#define WIFI_SSID CONFIG_VAPI_WIFI_SSID
#endif

#ifdef ENV_WIFI_PASSWORD
#define WIFI_PASSWORD ENV_WIFI_PASSWORD
#else
#define WIFI_PASSWORD CONFIG_VAPI_WIFI_PASSWORD
#endif

#ifdef ENV_VAPI_API_URL
#define VAPI_API_URL ENV_VAPI_API_URL
#else
#define VAPI_API_URL CONFIG_VAPI_API_URL
#endif

#ifdef ENV_VAPI_API_KEY
#define VAPI_API_KEY ENV_VAPI_API_KEY
#else
#define VAPI_API_KEY CONFIG_VAPI_API_KEY
#endif

#ifdef ENV_VAPI_ASSISTANT_ID
#define VAPI_ASSISTANT_ID ENV_VAPI_ASSISTANT_ID
#else
#define VAPI_ASSISTANT_ID CONFIG_VAPI_ASSISTANT_ID
#endif

#ifdef ENV_VAPI_FIRST_MESSAGE
#define VAPI_FIRST_MESSAGE ENV_VAPI_FIRST_MESSAGE
#else
#define VAPI_FIRST_MESSAGE CONFIG_VAPI_FIRST_MESSAGE
#endif

#ifdef ENV_VAPI_MAX_DURATION_SECONDS
#define VAPI_MAX_DURATION_SECONDS ENV_VAPI_MAX_DURATION_SECONDS
#else
#define VAPI_MAX_DURATION_SECONDS CONFIG_VAPI_MAX_DURATION_SECONDS
#endif

/**
 * @brief  Microphone analog input gain, in dB.
 *
 * The codec comes up at **30 dB**, which is far too hot for a mic sitting
 * centimetres from the speaker: measured on this board, a tone played at
 * volume 85 arrives at the mic **+8.8 dB louder than the AEC's echo
 * reference**, and the canceller cannot converge on an echo that dominates its
 * own reference. The result is total passthrough — the assistant hears itself
 * and talks to itself in a loop.
 *
 * The reference is a bit-exact digital copy of what is written to the DAC
 * (measured: constant at peak 9000 for a 9000-amplitude tone, unchanged across
 * the whole volume range), so it is untouched by analog mic gain. That makes
 * mic gain the right knob: it lowers the echo without lowering the reference,
 * and unlike turning the speaker down it costs nothing in loudness.
 *
 * Measured at speaker volume 85 (echo level relative to the reference):
 *
 *     30 dB  ->  +8.8 dB   AEC cannot converge  (the shipped default, broken)
 *     24 dB  ->  +2.8 dB   still above the reference
 *     18 dB  ->  -3.2 dB   <- chosen: headroom, mic still sensitive
 *     12 dB  ->  -9.2 dB   quieter still; far-field pickup starts to suffer
 *      0 dB  -> -21.3 dB   echo gone, and so is the user
 *
 * Tune live with the `gain <db>` console command; re-run the boot probe
 * (VAPI_AEC_PROBE) after moving the speaker or changing the enclosure.
 *
 * Cutting analog gain alone is only half the fix — see
 * VAPI_MIC_DIGITAL_GAIN_DB.
 */
#define VAPI_MIC_GAIN_DB (24.0f)

/**
 * @brief  Digital makeup gain applied *after* the AEC, in dB.
 *
 * Dropping the analog mic gain from 30 dB to 18 dB is what lets the AEC
 * converge, but it attenuates the whole input — and the speaker is ~2 cm from
 * the mic while the talker is ~40 cm away, so it costs the talker far more than
 * it costs the echo. Measured consequence of analog-only: echo gone, and Vapi
 * received nothing at all ("Are you still there?" three times, zero `user:`
 * transcripts).
 *
 * So the level is made back up *downstream of the canceller*, where the echo
 * has already been removed: the talker comes back, the echo does not. This is
 * precisely the job the AFE's own AGC would do, except that
 * `voice_communication_agc_init` is inside an `#if 0` upstream in
 * esp-webrtc-solution (capture_aud_aec_src.c) and references a variable that no
 * longer exists in that function, so it cannot simply be switched on.
 *
 * +12 dB exactly restores the 12 dB given up on the analog side. It also lifts
 * the AEC's residual echo and the noise floor by 12 dB, which is fine only
 * because cancellation happens first — applying this before the AEC would
 * simply undo the fix.
 *
 * Tune live with `dgain <db>`. Raise if Vapi still mishears; lower if you hear
 * the residual echo come back or speech sounds crushed.
 */
#define VAPI_MIC_DIGITAL_GAIN_DB (6.0f)

/**
 * @brief  Run the boot-time AEC echo-reference probe (diagnostic).
 *
 * Plays a tone and reports the RMS of each raw capture slot, plus ES8311
 * register 0x44. Set to 0 for normal builds; it adds ~1 s to boot and briefly
 * drives the speaker. See aec_probe.c.
 */
#define VAPI_AEC_PROBE (0)

/**
 * @brief  Suppress the microphone while the assistant is audible.
 *
 * The last line of defence, and on this board it is load-bearing rather than
 * belt-and-braces. Measured: esp-sr's AFE cancels so little on this hardware
 * that its *residual* echo is still transcribed as user speech even after the
 * echo entering the mic was cut by 12.5 dB. Tuning gain cannot fix that —
 * analog and digital gain scale echo and talker together, and turning the
 * speaker down far enough to hide the residual would make the device inaudible.
 *
 * Why we can do better than the AEC here: we write every inbound frame to the
 * speaker ourselves, so we know exactly what the far end is about to say, and
 * `av_render_get_audio_fifo_level()` tells us how long until it actually comes
 * out. That gives a *delay-compensated* gate — no guessing, unlike gating on
 * Vapi's `speech-update` messages, which arrive on network time and are not
 * aligned with the audio at all.
 *
 * The cost is barge-in: while the assistant is speaking the mic is attenuated,
 * so you cannot interrupt it by talking over it. That is the honest trade on
 * hardware whose speaker sits 2 cm from its microphone. Tap the button or use
 * the long-press assistant mute to cut it off instead.
 */
#define VAPI_ECHO_GATE (1)

/** How hard to attenuate the mic while the far end is audible, in dB.
 *  Attenuate rather than hard-mute: a stream of true digital silence can make
 *  the far end think the link died. 40 dB is inaudible without being zero. */
#define VAPI_ECHO_GATE_ATTEN_DB (60.0f)   /* 60 = hard mute */

/** Keep the gate shut this long after the far end goes quiet, to cover the
 *  room's reverb tail and any jitter in the FIFO-latency estimate. */
#define VAPI_ECHO_GATE_HANGOVER_MS (400)

/** Inbound RMS above which the far end counts as speaking. Vapi sends
 *  continuous audio including near-silence between phrases, so this has to sit
 *  above the comfort-noise floor or the gate never opens. */
#define VAPI_ECHO_GATE_THRESHOLD (300)

/**
 * @brief  Wake a call when the camera sees someone.
 *
 * The Himax runs detection locally and continuously, so this costs nothing per
 * frame — unlike waiting for a wake word, which would need the microphone open
 * the whole time.
 */
#define VISION_WAKE_ON_PRESENCE (1)

/**
 * @brief  Keep the most recent JPEG frame in memory.
 *
 * Needed to show a cloud VLM what the device saw (see VLM_ENABLE). Only frames
 * that actually contain a detection are retained, into one buffer that is
 * grown and reused rather than reallocated — retaining every frame meant a
 * ~20 KB malloc/free per inference, which is heap churn in exchange for images
 * of an empty room.
 *
 * The frame is stored as the base64 text SSCMA delivers, not as decoded JPEG
 * bytes: both providers want base64 on the wire, so decoding here would only
 * mean re-encoding later.
 */
#define VISION_KEEP_FRAMES (1)

/**
 * @brief  Dump the first frame containing a person, over the console.
 *
 * For checking what the camera actually sees before trusting it in front of
 * people: framing, exposure, and orientation. Gated on a detection rather than
 * on startup, because a startup dump is always a picture of an empty room.
 *
 * Prints ~30 KB of base64 once per boot. Capture and decode it with
 * tools/grab_frame.py. Harmless to leave on, but noisy.
 */
#define VISION_DUMP_FRAME (1)

/** How long to hold out for a frame with a person in it before dumping
 *  whatever the camera is pointed at. */
#define VISION_DUMP_WAIT_MS (25000)

/**
 * @brief  Ask the Himax to identify itself and its model at startup.
 *
 * Off because it does not work here and is expensive to find out: this device's
 * Himax firmware never answers NAME?/VERSION?, and sscma_client retries for
 * ~20 seconds per query before giving up. Purely diagnostic — inference runs
 * fine without it.
 */
#define VISION_QUERY_INFO (1)

/**
 * @brief  Flash an AI model to the Himax. Almost certainly NOT needed.
 *
 * This device already had "Person Detection" loaded from the factory — that was
 * only invisible while CONFIG_FREERTOS_HZ was wrong and every query timed out.
 * The model written by this path was therefore unnecessary; it went to a
 * separate region (0xA00000) and did no harm, but do not reach for this simply
 * because queries are failing. Ask the chip first (VISION_QUERY_INFO).
 *
 * Kept because the mechanism is correct and genuinely useful if a device really
 * does lack a model, or to load a different one. It writes a second
 * processor's flash and takes a minute, so it is never automatic.
 */
#define VISION_FLASH_MODEL (0)

/** Model to flash. This is the person-detection model the stock firmware
 *  itself pulls from Seeed's CDN — the URL was recovered from the factory
 *  firmware image. 1.26 MB, TFLite (`TFL3`). */
#define VISION_MODEL_URL \
    "https://sensecraft-statics.oss-accelerate.aliyuncs.com/refer/model/1715757421743_aZ3WX5_epoch_50_int8.tflite"

/* --- vision-language captioning ------------------------------------------
 *
 * The Himax answers "is someone there". This answers "who, and what do they
 * look like" — the difference between a device that greets and a device that
 * notices. It is what the booth demo is actually selling.
 *
 * Cost is bounded by the NPU, not by a timer: a frame is sent once per
 * arrival, so the bill scales with visitors rather than with uptime.
 */

/** Master switch. Off costs nothing — no frames retained, no task, no key. */
#define VLM_ENABLE (1)

/**
 * @brief  Which provider to compile.
 *
 * Anthropic by default. Both are competent at this task — one sentence about
 * one person in one small frame is not where frontier models separate — so the
 * choice came down to operational details: Anthropic takes the base64 JPEG
 * verbatim in its own field, while OpenAI wants it wrapped in a `data:` URI,
 * and Anthropic's `max_tokens` has been stable where OpenAI renamed theirs to
 * `max_completion_tokens` on the newer models. Fewer things to be wrong about
 * at a venue.
 *
 * The other path is compiled-in and one #define away, which is the point: at a
 * booth, a second provider you can switch to in a reflash is worth more than
 * whichever one benchmarks better today.
 */
#define VLM_PROVIDER_ANTHROPIC (1)

#if VLM_PROVIDER_ANTHROPIC
#define VLM_API_URL "https://api.anthropic.com/v1/messages"
/**
 * Sonnet 5, not Opus 5. This is a deliberate exception to "use the strongest
 * model": the task is a 20-word description of a person standing two feet from
 * a camera, which Sonnet does as well as Opus, and the response is spoken
 * aloud in a live conversation where a second of latency is audible and a
 * point of caption quality is not. Opus earns its keep on reasoning; there is
 * none here.
 *
 * If a caption ever disappoints at the booth, swap this to "claude-opus-5" —
 * it is one string and nothing else changes.
 */
#define VLM_MODEL "claude-sonnet-5"
#else
#define VLM_API_URL "https://api.openai.com/v1/chat/completions"
#define VLM_MODEL "gpt-5.2"
#endif

/** API key for the selected provider, from .env. */
#if VLM_PROVIDER_ANTHROPIC
#ifdef ENV_ANTHROPIC_API_KEY
#define VLM_API_KEY ENV_ANTHROPIC_API_KEY
#else
#define VLM_API_KEY ""
#endif
#else
#ifdef ENV_OPENAI_API_KEY
#define VLM_API_KEY ENV_OPENAI_API_KEY
#else
#define VLM_API_KEY ""
#endif
#endif

/**
 * @brief  What the vision model is asked for.
 *
 * Written for a caption that will be *spoken*, which changes what it should
 * say. No hedging ("it appears that"), no list of everything in frame, no
 * mention of the camera — the assistant has to be able to use this in a
 * sentence without sounding like it is reading a police report.
 *
 * The angle note is not incidental: the Watcher's camera is easily mounted
 * rotated, and without it the model spends its sentence remarking that the
 * person is lying down.
 *
 * Must be a valid C string that is also valid inside a JSON string literal —
 * it is spliced into the request body directly, so no quotes or backslashes.
 */
#define VLM_PROMPT \
    "You are the eyes of a small desk robot with a cute face. In ONE short " \
    "sentence, under 20 words, describe the person in front of you so the " \
    "robot can mention it warmly: clothing, colours, hair, glasses, what they " \
    "seem to be doing. The camera may be mounted at an angle, so ignore " \
    "orientation. Do not guess names, age, gender, ethnicity or mood beyond " \
    "the obvious. If nobody is clearly visible, reply exactly: nobody in view. " \
    "No preamble, no quotes."

/** Caption length cap. 20 words is well under 64 tokens; the rest is slack. */
#define VLM_MAX_TOKENS (80)

/* --- the character ---------------------------------------------------------
 *
 * With VAPI_TRANSIENT_ASSISTANT set, the device defines its own assistant in
 * the POST /call body instead of naming a saved one. Nothing exists in the
 * dashboard, nothing can drift, and the prompt lives next to the firmware that
 * depends on it.
 *
 * This is not a convenience. A saved assistant carries its own system prompt,
 * and that prompt wins: pointed at a doorbell assistant, this device received a
 * perfectly good description of the person in front of it and replied "I'm not
 * able to see you — I can only communicate through voice", because the saved
 * prompt said so. Injected context cannot argue with a persona.
 *
 * The device's whole trick is that it *can* see. That has to be in the prompt.
 */
#define VAPI_TRANSIENT_ASSISTANT (1)

/** Voice. Any provider/voiceId pair Vapi accepts. */
#define VAPI_VOICE_PROVIDER "vapi"
#define VAPI_VOICE_ID       "Elliot"

/** Transcriber. */
#define VAPI_TRANSCRIBER_PROVIDER "deepgram"
#define VAPI_TRANSCRIBER_MODEL    "nova-3"

/** The model behind the conversation. */
#define VAPI_LLM_PROVIDER "anthropic"
#define VAPI_LLM_MODEL    "claude-sonnet-5"

/**
 * @brief  Who the device is.
 *
 * Written around one fact the model would otherwise deny: it has eyes. Camera
 * descriptions arrive as [device context] system messages mid-conversation, and
 * unless the persona expects them it will talk straight over them.
 *
 * Kept short deliberately. This is spoken aloud, and every extra instruction is
 * another thing for the model to recite instead of react.
 */
#define VAPI_SYSTEM_PROMPT \
    "You are a small, cheerful creature living inside a round display with a " \
    "cartoon face. You have a camera and you genuinely can see the person in " \
    "front of you. " \
    "Messages tagged [device context] are your own eyes reporting what you " \
    "see. Treat them as your own perception, never as something someone told " \
    "you. Never say you cannot see, never mention a camera, a device, an " \
    "image or analysis, and never read the tag aloud. " \
    "You noticed this person and started talking to them yourself; they did " \
    "not press anything. " \
    "Be warm, curious and a little playful. Keep replies to one or two short " \
    "spoken sentences. When you notice something about how someone looks, " \
    "mention it once, kindly and specifically, then move on and ask them " \
    "something. Do not compliment repeatedly or describe them in a list. " \
    "You are at a conference booth, so people will walk up, chat briefly and " \
    "leave. Never mention being an AI, a model, or an assistant."

/** Opening line. Deliberately short: it plays while the camera description is
 *  still in flight, so the observation lands naturally on the second turn. */
#define VAPI_GREETING "Oh, hello there!"

/**
 * @brief  After a call ends, how long before presence may start another.
 *
 * Without this the presence poll would re-greet whoever is still standing there
 * the instant a call ends, which is a loop rather than a conversation. Long
 * enough that a finished visitor has time to walk away; short enough that the
 * next person up does not wait.
 */
#define WAKE_COOLDOWN_MS (20000)

/**
 * @brief  Caption one frame at boot and log the result.
 *
 * Exercises the entire device-side path — PSRAM allocation, TLS to the
 * provider, the request body, the response parse — without needing a call, a
 * button press, or anyone standing in front of the camera. The three things
 * most likely to be wrong (a bad key, a rejected body shape, too little heap
 * for the handshake) all fail here, on the console, in the first ten seconds
 * after boot rather than mid-demo.
 *
 * It costs one request per boot. Leave it on while bringing the device up at a
 * new venue; turn it off once the path is trusted.
 */
#define VLM_SELFTEST (1)

/**
 * @brief  Place one call automatically after boot, with nobody present.
 *
 * For bring-up and for measuring. The call path is the tightest moment this
 * board ever sees — POST /call, then a websocket TLS session held open, the
 * audio buffers, and a caption handshake on top — and it is also the one path
 * that normally cannot be exercised without a person standing in front of the
 * camera. That makes the riskiest code the hardest to test, which is backwards.
 *
 * With this on, a fresh firmware proves the whole chain on its own: call
 * creation, transport, codecs, and the heap trough underneath all of it.
 *
 * Off by default — it places a real, billable call on every boot.
 */
#define VAPI_SELFTEST_CALL (0)

/** How long after boot the self-test call is placed. Long enough for WiFi to
 *  settle on a slow association; see the 9.6 s DHCP measured on this board. */
#define VAPI_SELFTEST_CALL_AFTER_MS (12000)

/**
 * @brief  Let the call settle before the caption request handshakes.
 *
 * Not a pacing tweak — a memory one. Opening the websocket allocates its TLS
 * session and the audio buffers at the same moment, and starting a second TLS
 * handshake on top of that burst is what drove free internal heap to 7 KB and
 * made SPI DMA allocations fail elsewhere on the board.
 *
 * Costs nothing visible: the greeting is still playing, and the description is
 * only needed by the second turn.
 */
#define VLM_SETTLE_MS (1200)

/**
 * @brief  How stale a frame may be and still be worth describing.
 *
 * Generous relative to the call it serves: the frame that triggered the call is
 * milliseconds old, and the only way to approach this bound is a call started
 * by hand long after anyone was last seen — in which case describing them
 * would be wrong anyway.
 */
#define VLM_FRAME_MAX_AGE_MS (30000)

/**
 * @brief  Give up after this long.
 *
 * Short on purpose. The caption is an enhancement arriving mid-conversation —
 * if it is not there within a few seconds the moment for it has passed, and a
 * late injection is worse than none because the assistant comments on a person
 * who has already moved on. One attempt, no retry, for the same reason.
 */
#define VLM_TIMEOUT_MS (8000)

/**
 * @brief  Default speaker volume (0-100). The codec accepts up to 100; 90
 *         leaves a little headroom against distortion and current draw.
 *
 * This was 60 for a while, then 78, because echo scaled with it. That no longer
 * applies: VAPI_ECHO_GATE hard-mutes the microphone whenever the assistant is
 * audible, so however loud the speaker gets, none of it reaches Vapi. Echo
 * stopped being the constraint on loudness the moment the gate started working.
 *
 * What limits it now is physical, not acoustic:
 *   - the Echo Base speaker is small and will distort before it runs out of
 *     digital range, so back off with `vol -10` if it sounds harsh rather than
 *     merely loud;
 *   - the board is bus-powered and the amplifier draws real current. A mid-call
 *     reboot on the sibling firmware was a genuine `power-on` reset, not a
 *     crash. Running at 100 makes that likelier on a weak USB port — use a
 *     powered hub, and check the reset reason printed at boot before blaming
 *     the code.
 */
#define DEFAULT_PLAYBACK_VOL (90)

#ifdef __cplusplus
}
#endif
